import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navbar/page";
import { Toaster } from "sonner";
import { Inter } from 'next/font/google'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} font-sans`}
      suppressHydrationWarning
    >
      <body className="min-h-screen bg-background text-foreground relative overflow-x-hidden">
        {/* Background Decorative Elements */}
        <div className="fixed inset-0 -z-10 overflow-hidden pointer-events-none">
          <div className="absolute -top-[10%] -left-[10%] w-[40%] h-[40%] bg-primary/10 rounded-full blur-[120px] animate-pulse" />
          <div className="absolute top-[20%] -right-[5%] w-[30%] h-[30%] bg-green-400/10 rounded-full blur-[100px] animate-float" />
          <div className="absolute -bottom-[10%] left-[20%] w-[50%] h-[50%] bg-primary/5 rounded-full blur-[150px]" />
        </div>

        <Toaster position="top-center" richColors />
        <Navbar />
        
        <main className="flex-1">
          {children}
        </main>
        
        {/* Simple Footer Placeholder or real footer could go here */}
        <footer className="py-10 border-t border-border mt-20 glass dark:glass-dark">
          <div className="max-w-7xl mx-auto px-4 text-center text-muted-foreground text-sm">
            © 2026 FreshCart E-Commerce. All rights reserved.
          </div>
        </footer>
      </body>
    </html>
  );
}
